/* Generated by lungo 1.65.2807 from Lean 4.34.1 for program tagged_urn_formal. Do not edit. */
#include "tagged_urn_formal.h"
#include "tagged_urn_formal_program.h"

static const uint8_t sig_0[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_1[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_2[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x10, 0x15, 0x17, 0x10, 0x1b, 0x01, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t sig_3[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};
static const uint8_t sig_4[] = {
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00,
};
static const uint8_t sig_5[] = {
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x1b, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x1b, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
};

void tagged_urn_formal_initialize(void) {
    tagged_urn_formal__initialize();
}

lungo_type *tagged_urn_formal_wf_type(void) {
    return lungo_type_inductive(tagged_urn_formal__types(), 0, NULL, 0);
}

lungo_type *tagged_urn_formal_constraint_type(void) {
    return lungo_type_inductive(tagged_urn_formal__types(), 1, NULL, 0);
}
lungo_value *tagged_urn_formal_constraint_missing(void) {
    return lungo_value_ctor(0, NULL, 0);
}
lungo_value *tagged_urn_formal_constraint_unconstrained(void) {
    return lungo_value_ctor(1, NULL, 0);
}
lungo_value *tagged_urn_formal_constraint_optional_not(lungo_value *value) {
    lungo_value *fields[1] = {value};
    return lungo_value_ctor(2, fields, 1);
}
const lungo_value *tagged_urn_formal_constraint_optional_not_value(const lungo_value *v) {
    return lungo_value_ctor_field(v, 2, 0);
}
lungo_value *tagged_urn_formal_constraint_present(void) {
    return lungo_value_ctor(3, NULL, 0);
}
lungo_value *tagged_urn_formal_constraint_present_not(lungo_value *value) {
    lungo_value *fields[1] = {value};
    return lungo_value_ctor(4, fields, 1);
}
const lungo_value *tagged_urn_formal_constraint_present_not_value(const lungo_value *v) {
    return lungo_value_ctor_field(v, 4, 0);
}
lungo_value *tagged_urn_formal_constraint_exact(lungo_value *value) {
    lungo_value *fields[1] = {value};
    return lungo_value_ctor(5, fields, 1);
}
const lungo_value *tagged_urn_formal_constraint_exact_value(const lungo_value *v) {
    return lungo_value_ctor_field(v, 5, 0);
}
lungo_value *tagged_urn_formal_constraint_absent(void) {
    return lungo_value_ctor(6, NULL, 0);
}

int32_t tagged_urn_formal_comparable(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {a, b};
    return lungo_invoke(tagged_urn_formal__types(), tagged_urn_formal__call_l_TaggedUrn_dExec_dcomparable, sig_0, sizeof sig_0, NULL, 0, args, 2, result, error);
}

int32_t tagged_urn_formal_equivalent(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {a, b};
    return lungo_invoke(tagged_urn_formal__types(), tagged_urn_formal__call_l_TaggedUrn_dExec_dequivalent, sig_1, sizeof sig_1, NULL, 0, args, 2, result, error);
}

int32_t tagged_urn_formal_make(const lungo_value *scheme, const lungo_value *tags, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {scheme, tags};
    return lungo_invoke(tagged_urn_formal__types(), tagged_urn_formal__call_l_TaggedUrn_dExec_dmake, sig_2, sizeof sig_2, NULL, 0, args, 2, result, error);
}

int32_t tagged_urn_formal_refines(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {a, b};
    return lungo_invoke(tagged_urn_formal__types(), tagged_urn_formal__call_l_TaggedUrn_dExec_drefines, sig_3, sizeof sig_3, NULL, 0, args, 2, result, error);
}

int32_t tagged_urn_formal_specificity(const lungo_value *a, lungo_value **result, lungo_error **error) {
    const lungo_value *args[1] = {a};
    return lungo_invoke(tagged_urn_formal__types(), tagged_urn_formal__call_l_TaggedUrn_dExec_dspecificity, sig_4, sizeof sig_4, NULL, 0, args, 1, result, error);
}

int32_t tagged_urn_formal_values_match(const lungo_value *inst, const lungo_value *patt, lungo_value **result, lungo_error **error) {
    const lungo_value *args[2] = {inst, patt};
    return lungo_invoke(tagged_urn_formal__types(), tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMatch, sig_5, sizeof sig_5, NULL, 0, args, 2, result, error);
}

