/* Generated by lungo 1.106.540 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Lean.Data.Iterators.Producers.PersistentHashMap. */
#include "tagged_urn_formal_program.h"

/* Lean: List.foldr._at_.List.sum._at_.Lean.PersistentHashMap.subarrayMeasure.spec_2.spec_2 */
/* Compiled from: List.foldr */
/* Source: <lean>/Init/Data/List/Basic.lean:533:1 */
lungo_obj tagged_urn_formal__l_List_dfoldr_d__at___dList_dsum_d__at___dLean_dPersistentHashMap_dsubarrayMeasure_dspec__2_dspec__2(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_inc(x_1);
            return x_1;
        }
        default: {
            x_3 = lungo_ctor_get(x_2, 0);
            x_4 = lungo_ctor_get(x_2, 1);
            x_5 = tagged_urn_formal__l_List_dfoldr_d__at___dList_dsum_d__at___dLean_dPersistentHashMap_dsubarrayMeasure_dspec__2_dspec__2(x_1, x_4);
            x_6 = tagged_urn_formal__l_Nat_dadd(x_3, x_5);
            lungo_dec(x_5);
            return x_6;
        }
    }
}

/* Lean: List.sum._at_.Lean.PersistentHashMap.subarrayMeasure.spec_2 */
/* Compiled from: List.sum */
/* Source: <lean>/Init/Data/List/Basic.lean:2062:1 */
lungo_obj tagged_urn_formal__l_List_dsum_d__at___dLean_dPersistentHashMap_dsubarrayMeasure_dspec__2(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    x_2 = lungo_usize_to_nat(0u);
    x_3 = tagged_urn_formal__l_List_dfoldr_d__at___dList_dsum_d__at___dLean_dPersistentHashMap_dsubarrayMeasure_dspec__2_dspec__2(x_2, x_1);
    return x_3;
}

