/* Generated by lungo 1.83.0 from Lean 4.34.1 for program tagged_urn_formal. Do not edit. */
#ifndef TAGGED_URN_FORMAL_ENTRIES_H
#define TAGGED_URN_FORMAL_ENTRIES_H
#include "lungo.h"
const lungo_types *tagged_urn_formal__types(void);
void tagged_urn_formal__set_host_extern(size_t index, uint64_t callback);
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dcomparable(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dequivalent(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dmake(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dmeets(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dmeetsClosed(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_drefines(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_drefinesClosed(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dspecificity(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMatch(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMatchClosed(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMeet(const uint8_t *input, size_t len, lungo_buffer *out);
#endif /* TAGGED_URN_FORMAL_ENTRIES_H */
