/* Generated by lungo 1.76.3233 from Lean 4.34.1 for program tagged_urn_formal. Do not edit. */
#ifndef TAGGED_URN_FORMAL_H
#define TAGGED_URN_FORMAL_H

#include "lungo.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Initializes the program; every function initializes it on first use. */
void tagged_urn_formal_initialize(void);

/* TaggedUrn.Exec.Wf */
#define TAGGED_URN_FORMAL_WF_FINGERPRINT "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785"
lungo_type *tagged_urn_formal_wf_type(void);

/* TaggedUrn.Constraint */
#define TAGGED_URN_FORMAL_CONSTRAINT_FINGERPRINT "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7"
lungo_type *tagged_urn_formal_constraint_type(void);
#define TAGGED_URN_FORMAL_CONSTRAINT_MISSING 0
/* TaggedUrn.Constraint.missing; takes ownership of the fields. */
lungo_value *tagged_urn_formal_constraint_missing(void);
#define TAGGED_URN_FORMAL_CONSTRAINT_UNCONSTRAINED 1
/* TaggedUrn.Constraint.unconstrained; takes ownership of the fields. */
lungo_value *tagged_urn_formal_constraint_unconstrained(void);
#define TAGGED_URN_FORMAL_CONSTRAINT_OPTIONAL_NOT 2
/* TaggedUrn.Constraint.optionalNot; takes ownership of the fields. */
lungo_value *tagged_urn_formal_constraint_optional_not(lungo_value *value);
/* Field value of TaggedUrn.Constraint.optionalNot (borrowed). */
const lungo_value *tagged_urn_formal_constraint_optional_not_value(const lungo_value *v);
#define TAGGED_URN_FORMAL_CONSTRAINT_PRESENT 3
/* TaggedUrn.Constraint.present; takes ownership of the fields. */
lungo_value *tagged_urn_formal_constraint_present(void);
#define TAGGED_URN_FORMAL_CONSTRAINT_PRESENT_NOT 4
/* TaggedUrn.Constraint.presentNot; takes ownership of the fields. */
lungo_value *tagged_urn_formal_constraint_present_not(lungo_value *value);
/* Field value of TaggedUrn.Constraint.presentNot (borrowed). */
const lungo_value *tagged_urn_formal_constraint_present_not_value(const lungo_value *v);
#define TAGGED_URN_FORMAL_CONSTRAINT_EXACT 5
/* TaggedUrn.Constraint.exact; takes ownership of the fields. */
lungo_value *tagged_urn_formal_constraint_exact(lungo_value *value);
/* Field value of TaggedUrn.Constraint.exact (borrowed). */
const lungo_value *tagged_urn_formal_constraint_exact_value(const lungo_value *v);
#define TAGGED_URN_FORMAL_CONSTRAINT_ABSENT 6
/* TaggedUrn.Constraint.absent; takes ownership of the fields. */
lungo_value *tagged_urn_formal_constraint_absent(void);

/* TaggedUrn.Exec.comparable : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t tagged_urn_formal_comparable(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error);

/* TaggedUrn.Exec.equivalent : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t tagged_urn_formal_equivalent(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error);

/* TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t tagged_urn_formal_make(const lungo_value *scheme, const lungo_value *tags, lungo_value **result, lungo_error **error);

/* TaggedUrn.Exec.refines : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t tagged_urn_formal_refines(const lungo_value *a, const lungo_value *b, lungo_value **result, lungo_error **error);

/* TaggedUrn.Exec.specificity : TaggedUrn.Exec.Wf → Nat */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t tagged_urn_formal_specificity(const lungo_value *a, lungo_value **result, lungo_error **error);

/* TaggedUrn.Exec.valuesMatch : TaggedUrn.Constraint → TaggedUrn.Constraint → Bool */
/* Returns LUNGO_OK with the result, or LUNGO_MALFORMED if the arguments do not match. */
int32_t tagged_urn_formal_values_match(const lungo_value *inst, const lungo_value *patt, lungo_value **result, lungo_error **error);

#ifdef __cplusplus
}
#endif

#endif /* TAGGED_URN_FORMAL_H */
