// Generated by lungo 1.71.2897 from Lean 4.34.1 for program tagged_urn_formal. Do not edit.

import LungoKit
import TaggedUrnFormalProgram

/// The Lean program tagged_urn_formal.
let program = LungoProgram(types: tagged_urn_formal__types())

/// Calls an entry point of the program with `input`; its status and output.
func entry(_ f: @escaping (UnsafePointer<UInt8>?, Int, UnsafeMutablePointer<lungo_buffer>?) -> Int32) -> LungoCall {
    { input, count in
        var buf = lungo_buffer()
        let status = f(input, count, &buf)
        let out = buf.len > 0 ? Array(UnsafeBufferPointer(start: buf.data, count: Int(buf.len))) : []
        lungo_buffer_free(&buf)
        return (status, out)
    }
}

/// Lean's TaggedUrn.Exec.Wf, held by handle: only the program's functions make and read its values.
public struct Wf: @unchecked Sendable {
    let value: LungoOpaque

    /// Releases the value; using it afterwards fails with `LungoMalformed`.
    public func close() { value.close() }
}

extension Wf {
    /// The layout fingerprint of Lean's TaggedUrn.Exec.Wf.
    public static var lungoFingerprint: String { "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785" }

    /// Describes TaggedUrn.Exec.Wf for polymorphic functions.
    public static var lungoType: LungoType<Wf> {
        LungoType<Wf>(
            expr: Lungo.inductiveExpr(0),
            encode: { w, v in try Lungo.opaque.encode(&w, v.value) },
            decode: { r in Wf(value: try Lungo.opaque.decode(&r)) })
    }
}

/// Lean's TaggedUrn.Constraint.
public indirect enum Constraint {
    /// Lean's TaggedUrn.Constraint.missing.
    case missing
    /// Lean's TaggedUrn.Constraint.unconstrained.
    case unconstrained
    /// Lean's TaggedUrn.Constraint.optionalNot.
    case optionalNot(value: String)
    /// Lean's TaggedUrn.Constraint.present.
    case present
    /// Lean's TaggedUrn.Constraint.presentNot.
    case presentNot(value: String)
    /// Lean's TaggedUrn.Constraint.exact.
    case exact(value: String)
    /// Lean's TaggedUrn.Constraint.absent.
    case absent
}

extension Constraint: Equatable {}

extension Constraint {
    /// The layout fingerprint of Lean's TaggedUrn.Constraint.
    public static var lungoFingerprint: String { "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7" }

    /// Describes TaggedUrn.Constraint for polymorphic functions.
    public static var lungoType: LungoType<Constraint> {
        LungoType<Constraint>(
            expr: Lungo.inductiveExpr(1),
            encode: { w, v in
                switch v {
                case .missing:
                    w.u32(0)
                case .unconstrained:
                    w.u32(1)
                case .optionalNot(let value):
                    w.u32(2)
                    try Lungo.string.encode(&w, value)
                case .present:
                    w.u32(3)
                case .presentNot(let value):
                    w.u32(4)
                    try Lungo.string.encode(&w, value)
                case .exact(let value):
                    w.u32(5)
                    try Lungo.string.encode(&w, value)
                case .absent:
                    w.u32(6)
                }
            },
            decode: { r in
                switch try r.u32() {
                case 0: return .missing
                case 1: return .unconstrained
                case 2: return .optionalNot(value: try Lungo.string.decode(&r))
                case 3: return .present
                case 4: return .presentNot(value: try Lungo.string.decode(&r))
                case 5: return .exact(value: try Lungo.string.decode(&r))
                case 6: return .absent
                case let c: throw LungoMalformed("constructor index \(c) of TaggedUrn.Constraint")
                }
            })
    }
}

/// Lean's TaggedUrn.Exec.comparable : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool
public func comparable(_ a: Wf, _ b: Wf) throws -> Bool {
    try program.invoke(
        entry(tagged_urn_formal__call_l_TaggedUrn_dExec_dcomparable), typeArgs: [],
        args: { w in
            try Wf.lungoType.encode(&w, a)
            try Wf.lungoType.encode(&w, b)
        },
        returns: .value(Lungo.bool))
}

/// Lean's TaggedUrn.Exec.equivalent : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool
public func equivalent(_ a: Wf, _ b: Wf) throws -> Bool {
    try program.invoke(
        entry(tagged_urn_formal__call_l_TaggedUrn_dExec_dequivalent), typeArgs: [],
        args: { w in
            try Wf.lungoType.encode(&w, a)
            try Wf.lungoType.encode(&w, b)
        },
        returns: .value(Lungo.bool))
}

/// Lean's TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf
public func make(_ scheme: String, _ tags: [(String, Constraint)]) throws -> Wf? {
    try program.invoke(
        entry(tagged_urn_formal__call_l_TaggedUrn_dExec_dmake), typeArgs: [],
        args: { w in
            try Lungo.string.encode(&w, scheme)
            try Lungo.list(Lungo.pair(Lungo.string, Constraint.lungoType)).encode(&w, tags)
        },
        returns: .value(Lungo.option(Wf.lungoType)))
}

/// Lean's TaggedUrn.Exec.refines : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool
public func refines(_ a: Wf, _ b: Wf) throws -> Bool {
    try program.invoke(
        entry(tagged_urn_formal__call_l_TaggedUrn_dExec_drefines), typeArgs: [],
        args: { w in
            try Wf.lungoType.encode(&w, a)
            try Wf.lungoType.encode(&w, b)
        },
        returns: .value(Lungo.bool))
}

/// Lean's TaggedUrn.Exec.specificity : TaggedUrn.Exec.Wf → Nat
public func specificity(_ a: Wf) throws -> LungoNat {
    try program.invoke(
        entry(tagged_urn_formal__call_l_TaggedUrn_dExec_dspecificity), typeArgs: [],
        args: { w in
            try Wf.lungoType.encode(&w, a)
        },
        returns: .value(Lungo.nat))
}

/// Lean's TaggedUrn.Exec.valuesMatch : TaggedUrn.Constraint → TaggedUrn.Constraint → Bool
public func valuesMatch(_ inst: Constraint, _ patt: Constraint) throws -> Bool {
    try program.invoke(
        entry(tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMatch), typeArgs: [],
        args: { w in
            try Constraint.lungoType.encode(&w, inst)
            try Constraint.lungoType.encode(&w, patt)
        },
        returns: .value(Lungo.bool))
}
